-- CreateTable
CREATE TABLE "ISPU_Jakarta_2024" (
    "id" TEXT NOT NULL,
    "stasiun" TEXT NOT NULL,
    "pm10" DOUBLE PRECISION NOT NULL,
    "pm25" DOUBLE PRECISION NOT NULL,
    "so2" DOUBLE PRECISION NOT NULL,
    "o3" DOUBLE PRECISION NOT NULL,
    "co" DOUBLE PRECISION NOT NULL,
    "no2" DOUBLE PRECISION NOT NULL,
    "kategori" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ISPU_Jakarta_2024_pkey" PRIMARY KEY ("id")
);
